- name: Ensures grafana dirs exists
  file:
    path: "/opt/grafana/provisioning/{{ item }}"
    state: directory
    recurse: yes
  loop:
    - 'dashboards'
    - 'datasources'

- name: copy over grafana.ini
  template:
    src: grafana.ini
    dest: /opt/grafana/grafana.ini
  notify:
    - redeploy grafana container
  no_log: true

- name: add grafana datasources
  template:
    src: datasource.yaml
    dest: /opt/grafana/provisioning/datasources/default.yaml
  notify:
    - redeploy grafana container

- name: copy over dashboards
  copy:
    src: "{{ item }}"
    dest: "/opt/grafana/provisioning/dashboards/{{ item }}"
  loop:
    - mysql.json
    - logs.json
    - main.json
  notify:
    - redeploy grafana container

- name: add dashboard provisioning
  template:
    src: dashboard.yaml
    dest: /opt/grafana/provisioning/dashboards/default.yaml
  notify:
    - redeploy grafana container

- name: deploy grafana container
  docker_container:
    name: grafana
    image: grafana/grafana:8.3.3
    volumes: /opt/grafana:/etc/grafana
    published_ports: "{{ grafana_port }}:3000"
    state: started
    container_default_behavior: no_defaults
    restart_policy: always
  register: grafana_deploy
