- name: Install Grafana requirements
  apt:
    name:
     - ca-certificates
     - apt-transport-https
     - software-properties-common
     - wget

- name: get grafana key
  ansible.builtin.get_url:
    url: https://apt.grafana.com/gpg.key
    dest: /usr/share/keyrings/grafana.key

- name: add grafana repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/grafana.key] https://apt.grafana.com stable main"
    filename: grafana
    state: present

- name: install grafana
  apt:
    name: grafana
  register: grafana_installed

- name: start enable grafana server
  service:
    name: grafana-server
    state: started
    enabled: yes

- name: copy over grafana config
  template:
    src: grafana.ini
    dest: /etc/grafana/grafana.ini
  notify: restart grafana-server
  no_log: true

- name: set prometheus as datasource
  template:
    src: datasource.yaml
    dest: /etc/grafana/provisioning/datasources/prometheus.yaml
  notify: restart grafana-server

- name: Ensures dashboard dir exists
  file:
    path: /var/lib/grafana/dashboards/
    state: directory

- name: copy over main dashboard json
  copy:
    src: main.json
    dest: /var/lib/grafana/dashboards/prometheus.json
  notify: restart grafana-server

- name: copy over syslog dashboard json
  copy:
    src: logs.json
    dest: /var/lib/grafana/dashboards/logs.json
  notify: restart grafana-server

- name: add dashboard provisioning
  template:
    src: dashboard.yaml
    dest: /etc/grafana/provisioning/dashboards/prometheus.yaml
  notify: restart grafana-server
