- name: install uwsgi and uwsgi-plugin-python3
  apt:
    name:
      - uwsgi
      - uwsgi-plugin-python3
    state: latest

- name: Set agama config file
  template:
    src: agama.ini
    dest: /etc/uwsgi/apps-enabled/agama.ini
  notify: Restart uwsgi on config change
  no_log: true

- name: Start and enable uwsgi service
  service:
    name: uwsgi
    state: started
    enabled: yes
