{
 "title": "Home",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "NGINX Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(nginx_up{instance=\"nginx1:80\"} or 1-absent(nginx_up{instance=\"nginx1:80\"})) or (nginx_up{instance=\"nginx2:80\"} or 1-absent(nginx_up{instance=\"nginx2:80\"})) or (nginx_up{instance=\"nginx3:80\"} or 1-absent(nginx_up{instance=\"nginx3:80\"}))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "bind9 Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(bind_up{instance=\"ns1:80\"} or 1-absent(bind_up{instance=\"ns1:80\"})) or (bind_up{instance=\"ns2:80\"} or 1-absent(bind_up{instance=\"ns2:80\"})) or (bind_up{instance=\"ns3:80\"} or 1-absent(bind_up{instance=\"ns3:80\"}))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "keepalived_vrrp_state",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(keepalived_vrrp_state{instance=\"keepalived1:80\"} or 1-absent(keepalived_vrrp_state{instance=\"keepalived1:80\"})) or (keepalived_vrrp_state{instance=\"keepalived2:80\"} or 1-absent(keepalived_vrrp_state{instance=\"keepalived2:80\"}))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "mysql master slave",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(mysql_global_variables_read_only{instance=\"mysql1:80\"} or -absent(mysql_global_variables_read_only{instance=\"mysql1:80\"})) or (mysql_global_variables_read_only{instance=\"mysql2:80\"} or -absent(mysql_global_variables_read_only{instance=\"mysql2:80\"}))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "influxdb status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "influxdb_exporter_stats_query_success",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "haproxy status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(haproxy_backend_status{instance=\"lb1:80\"} or 1-absent(haproxy_backend_status{instance=\"lb1:80\"})) or (haproxy_backend_status{instance=\"lb2:80\"} or 1-absent(haproxy_backend_status{instance=\"lb2:80\"}))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "haproxy servers - lb1",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(haproxy_server_status{instance=\"lb1:80\", server=\"agama1\"} or 1-absent(haproxy_server_status{instance=\"lb1:80\", server=\"agama1\"})) or (haproxy_server_status{instance=\"lb1:80\", server=\"agama2\"} or 1-absent(haproxy_server_status{instance=\"lb1:80\", server=\"agama2\"})) or (haproxy_server_status{instance=\"lb1:80\", server=\"agama3\"} or 1-absent(haproxy_server_status{instance=\"lb1:80\", server=\"agama3\"})) or\n(haproxy_server_status{instance=\"lb1:80\", server=\"agama4\"} or 1-absent(haproxy_server_status{instance=\"lb1:80\", server=\"agama4\"}))",
     "legendFormat": "{{instance}} - {{server}}"
    }
   ]
  },
  {
   "title": "haproxy servers - lb2",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(haproxy_server_status{instance=\"lb2:80\", server=\"agama1\"} or 1-absent(haproxy_server_status{instance=\"lb2:80\", server=\"agama1\"})) or (haproxy_server_status{instance=\"lb2:80\", server=\"agama2\"} or 1-absent(haproxy_server_status{instance=\"lb2:80\", server=\"agama2\"})) or (haproxy_server_status{instance=\"lb2:80\", server=\"agama3\"} or 1-absent(haproxy_server_status{instance=\"lb2:80\", server=\"agama3\"})) or (haproxy_server_status{instance=\"lb2:80\", server=\"agama4\"} or 1-absent(haproxy_server_status{instance=\"lb2:80\", server=\"agama4\"}))",
     "legendFormat": "{{instance}} - {{server}}"
    }
   ]
  },
  {
   "title": "nginx requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bind9 requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum by (type)(rate(bind_resolver_queries_total[5m]))",
     "legendFormat": "dns {{instance}} {{type}}"
    }
   ]
  },
  {
   "title": "Influxdb write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(influxdb_write_write_ok[5m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rtt",
     "select": [
      [
       { "params": [ "rtt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "100 * (1 - ((node_memory_MemFree_bytes + node_memory_Cached_bytes + node_memory_Buffers_bytes) / node_memory_MemTotal_bytes))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "cpu usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "(1 - avg(irate(node_cpu_seconds_total{mode=\"idle\"}[10m])) by (instance)) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}