{
 "title": "Mysql",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "mysql master slave",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_read_only",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "mysql status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mysql_up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Server ID",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "mysql_global_variables_server_id"
    }
   ]
  },
  {
   "title": "mysql command rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(mysql_global_status_commands_total[5m]))",
     "legendFormat": "total comands"
    }
   ]
  }
 ]
}