- name: restart bind9
  ansible.builtin.service:
    name: bind9
    state: restarted

- name: rndc reload
  become: yes
  ansible.builtin.shell:
    cmd: "rndc reload"

- name: restart named
  service:
    name: named
    state: restarted