- name: ensure /opt/agama exists
  file:
    path: /opt/agama
    state: directory

- name: get agama Dockerfile
  get_url:
    url: "https://raw.githubusercontent.com/hudolejev/agama/master/Dockerfile"
    dest: "/opt/agama/Dockerfile"

- name: Download agama
  get_url:
    url: https://raw.githubusercontent.com/hudolejev/agama/master/agama.py
    dest: /opt/agama

- name: build agama docker image
  docker_image:
    name: agama
    source: build
    build:
      network: host
      path: /opt/agama

- name: gather existing AGAMA_DATABASE_URI env variable value
  command: "sudo docker exec -t agama env | grep AGAMA_DATABASE_URI= | cut -d '=' -f2"
  register: agama_database_uri
  changed_when: false
  failed_when: false
  no_log: true

- name: deploy agama container
  docker_container:
    name: "agama{{ item }}"
    image: agama:latest
    volumes: /opt/agama:/etc/agama
    pull: no
    restart_policy: always
    published_ports: "{{ agama_port + item }}:8000"
    state: started
    container_default_behavior: no_defaults
    env:
      AGAMA_DATABASE_URI: "{{ mysql_uri }}"
  when: "agama_database_uri.stdout != mysql_uri"
  loop:
    - 0
    - 1
  no_log: true
