- name: install prometheus mysqld exporter
  apt:
    name: prometheus-mysqld-exporter

- name: create MySQL user for exporter
  community.mysql.mysql_user:
    name: "{{ mysql_prometheus_user }}"
    password: "{{ mysql_prometheus_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  no_log: true

- name: copy over my.cnf for mysql exporter
  template:
    src: .my.cnf
    dest: /var/lib/prometheus/.my.cnf
  notify: Restart mysql exporter
  no_log: true

- name: grant mysql exporter user access
  mysql_query:
    query: "GRANT PROCESS, REPLICATION CLIENT, SELECT ON *.* TO '{{ mysql_prometheus_user }}'@'localhost';"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: copy over mysql exporter defaults file
  ansible.builtin.template:
    src: exporter_default
    dest: /etc/default/prometheus-mysqld-exporter
  notify: Restart mysql exporter
  no_log: true

- name: start enable mysql exporter service
  ansible.builtin.service:
    name: prometheus-mysqld-exporter
    enabled: yes
    state: started
