- name: Install mysql-server and python-mysqldb
  apt:
    name:
      - mysql-server
      - python3-pymysql
    state: latest

- name: Start and enable service 'mysql'
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: yes
  notify:
    - Reset MySQL source
    - Reset MySQL replica

- name: override conf
  template:
    src: mysql.cnf
    dest: /etc/mysql/mysql.conf.d/override.cnf
  notify:
    - Restart mysql on config change
    - Restart mysql exporter on config change

- name: create MySQL database 'agama'
  become: yes
  community.mysql.mysql_db:
    name: "{{ mysql_database }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: create MySQL user 'agama'
  community.mysql.mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    host: "%"
    priv: "{{ mysql_database }}.*:ALL"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  no_log: true

- name: create MySQL user 'replication'
  community.mysql.mysql_user:
    name: "{{ mysql_replication_user }}"
    password: "{{ mysql_replication_password }}"
    host: "%"
    priv: "*.*:REPLICATION SLAVE"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  no_log: true

- name: set replica read only
  community.mysql.mysql_variables:
    variable: read_only
    value: "{{ 'OFF' if inventory_hostname == mysql_host else 'ON' }}"
    mode: persist
    login_unix_socket: /var/run/mysqld/mysqld.sock
  notify:
    - Reset MySQL source
    - Reset MySQL replica