apiVersion: 1

datasources:
  - name: prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://{{ groups['prometheus'][0] }}/prometheus
    editable: true
  - name: influxdb:latency
    type: influxdb
    access: proxy
    url: "http://{{ groups['influxdb'][0] }}:{{ influxdb_port }}"
    editable: true
    database: latency
  - name: influxdb:telegraf
    type: influxdb
    access: proxy
    url: "http://{{ groups['influxdb'][0] }}:{{ influxdb_port }}"
    editable: true
    database: telegraf