- name: ensure /etc/keepalived exists
  file:
    path: /etc/keepalived/
    state: directory

- name: create keepalived_script user
  user:
    name: keepalived_script
    state: present

- name: copy over scripts
  template:
    src: keepalived_script
    dest: /etc/keepalived/keepalived_script
    mode: +x
  notify: restart keepalived

- name: copy over keepalived conf
  template:
    src: keepalived.conf
    dest: /etc/keepalived/keepalived.conf
  notify: restart keepalived

- name: install keepalived
  apt:
    name: keepalived
    state: present

- name: ensure /opt/keepalived/ exists
  file:
    path: /opt/keepalived/
    state: directory

- name: copy over keepalived monitoring install script
  copy:
    src: keepalive-monitor-install.sh
    dest: /opt/keepalived/keepalive-monitor-install.sh
    mode: +x
  register: keepalive_monitor_install

- name: install keepalived monitoring
  shell:
    cmd: /opt/keepalived/keepalive-monitor-install.sh
  when: keepalive_monitor_install.changed

- name: Add keepalived service
  template:
    src: prometheus-keepalived-exporter.service
    dest: /etc/systemd/system/prometheus-keepalived-exporter.service
  notify: restart keepalived exporter
  register: keepalived_service

- name: reload daemon
  shell:
    cmd: "systemctl daemon-reload"
  when: keepalived_service.changed

- name: start enable keepalived service
  service:
    name: keepalived
    state: started
    enabled: yes

- name: start enable keepalived exporter service
  service:
    name: prometheus-keepalived-exporter
    state: started
    enabled: yes