- name: install docker
  apt:
    name: docker.io

- name: install python3-docker
  apt:
    name: python3-docker

- name: start enable dockerd
  service:
    name: docker
    state: started
    enabled: yes