- name: Update APT cache
  apt:
    cache_valid_time: 86400


- name: get current hostname
  shell:
    cmd: hostname
  register: hostname
  changed_when: false

- name: set hostname when current one is not correct
  shell:
    cmd: "hostnamectl set-hostname {{ inventory_hostname }}"
  when: "'{{ inventory_hostname }}' != hostname.stdout"

- name: add hostname to /etc/hosts
  become: true
  blockinfile:
    path: /etc/hosts
    block: "localhost {{ inventory_hostname }}"