global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  external_labels:
      monitor: 'example'

alerting:
  alertmanagers:
  - static_configs:
    - targets: ['localhost:9093']

scrape_configs:
  - job_name: prometheus
    metrics_path: "/prometheus/metrics"
    static_configs:
      - targets: ['prometheus']

  - job_name: influxdb
    metrics_path: "/influxdb-metrics"
    static_configs:
      - targets: ["influxdb"]

  - job_name: node
    metrics_path: "/node-metrics"
    static_configs:
      - targets: ["node1", "node2", "node3"]

  - job_name: mysql
    metrics_path: "/mysql-metrics"
    static_configs:
      - targets: ["mysql1", "mysql2"]

  - job_name: nginx
    metrics_path: "/nginx-metrics"
    static_configs:
      - targets: ["nginx1", "nginx2", "nginx3"]

  - job_name: bind9
    metrics_path: "/bind-metrics"
    static_configs:
      - targets: ["ns1", "ns2", "ns3"]

  - job_name: haproxy
    metrics_path: "/haproxy-metrics"
    static_configs:
      - targets: ["lb1", "lb2"]

  - job_name: keepalived
    metrics_path: "/keepalived-metrics"
    static_configs:
      - targets: ["keepalived1", "keepalived2"]