global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  external_labels:
      monitor: 'example'

alerting:
  alertmanagers:
  - static_configs:
    - targets: ['localhost:9093']

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: "/prometheus/metrics"
    static_configs:
      - targets: [ "{{ groups['prometheus'] | join('", "') }}" ]

  - job_name: node
    metrics_path: "/node-metrics"
    static_configs:
      - targets: [ "{{ groups['all'] | join('", "') }}" ]

  - job_name: mysql
    metrics_path: "/mysql-metrics"
    static_configs:
      - targets: [ "{{ groups['db_servers'] | join('", "') }}" ]

  - job_name: nginx
    metrics_path: "/nginx-metrics"
    static_configs:
      - targets: [ "{{ groups['all'] | join('", "') }}" ]

  - job_name: bind9
    metrics_path: "/bind-metrics"
    static_configs:
      - targets: [ "{{ groups['dns_servers'] | join('", "') }}" ]