- name: add telegraf key
  apt_key:
    url: https://repos.influxdata.com/influxdb.key
    state: present

- name: add telegraf repository
  apt_repository:
    repo: "deb https://repos.influxdata.com/ubuntu bionic stable"
    filename: influxdb
    state: present

- name: install telegraf
  apt:
    name: telegraf
    state: present

- name: set up telegraf config file
  template:
    src: telegraf.conf
    dest: /etc/telegraf/telegraf.conf
  notify: restart telegraf